###

POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

###
POST http://localhost:8000/api/emails
Content-Type: application/json
Authorization: Bearer 2|IJBrkgbf7MTC18HRa3dSoavELd9Z2hOExbgA7nXu

{
    "emails": ["rhea.ardiente@mlhuillier.com",
                "quency.atacador@mlhuillier.com",
                "jenie.tomalon@mlhuillier.com",
                "shenna.caneda@mlhuillier.com",
                "reina.mates@mlhuillier.com",
                "rhea0951@gmail.com"
                ]
}

###
GET http://localhost:8000/api/email
Content-Type: application/json
Authorization: Bearer 1|C9KQpLkU6buLsyjTGntlDo61aI0XhtYVmw5iyd1E


###
GET http://localhost:8000/api/response
Authorization: Bearer 2|hdvbEV3qTokw50QYMpPZbtCZOFBE45Qk3So6NvR0


###

POST http://localhost:8000/api/forms
Content-Type: application/json
Authorization: Bearer 4|mmRV5944AlPpshXfIHkDCtpwQMBA9wOvsh4zKnv4

{
    "question1": "This is a test",
    "question2": "I am Beautitful",
    "question3": "Life is Challenging",
    "category1": "Good",
    "category2": "Fair",
    "category3": "Good",
    "category4": "Fair",
    "category5": "Outstanding",
    "category6": "Poor",
    "category7": "Fair",
    "category8": "Good",
    "category9": "Good",
    "category10": "Good"
}




// Deployed Testing

//LOGIN

###
POST https://mlproject-backend.herokuapp.com/api/login
Content-Type: application/json

{
    "email" : "rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

###
POST https://mlproject-backend.herokuapp.com/api/emails
Content-Type: application/json
Authorization: Bearer 1|LsXA2xIY0UO7niWttbkiuDvTKVBglGr9iWHqgrNv

{
    "emails": ["rhea.ardiente@mlhuillier.com",
                "quency.atacador@mlhuillier.com",
                "jonalyn.mobilla@mlhuillier.com",
                "shenna.caneda@mlhuillier.com",
                "reina.mates@mlhuillier.com",
                "rhea0951@gmail.com"
                ]
}

###
POST https://mlproject-backend.herokuapp.com/api/forms
Content-Type: application/json
Authorization: Bearer 1|nviU5a1voq9u6pqz8JtmARozo01c2tMCocxT8wqx

{
    "question1": "This is a test",
    "question2": "I am Beautitful",
    "question3": "Life is Challenging",
    "category1": "Good",
    "category2": "Fair",
    "category3": "Good",
    "category4": "Fair",
    "category5": "Outstanding",
    "category6": "Poor",
    "category7": "Fair",
    "category8": "Good",
    "category9": "Good",
    "category10": "Good"
}

###
GET https://mlproject-backend.herokuapp.com/api/response
Authorization: Bearer 1|nviU5a1voq9u6pqz8JtmARozo01c2tMCocxT8wqx
